apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Aplicação Python que mostra o host e as horas, chamado ${{values.app_name}}
  annotations:
    github.com/project-slug: MgtecnoInfoCloud/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental